version: "3.7"
services:
  mysql80:
    image: "mysql:8.0"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "********"
      MYSQL_DATABASE: "compete_ai"
    volumes:
      - ./scripts/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # 注意：如果你需要持久化数据，可以使用以下卷挂载，但请确保路径正确并且有适当的权限
      - ./mysql_data:/var/lib/mysql

  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"