// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import "CompeteAI/internal/app"

import "github.com/gin-gonic/gin"

func InitWebServer() *gin.Engine {
	return app.InitWebServer()
}
