// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"CompeteAI/internal/repository"
	"CompeteAI/internal/repository/cache"
	"CompeteAI/internal/repository/dao"
	"CompeteAI/internal/service"
	"CompeteAI/internal/web"
	"CompeteAI/internal/web/jwt"
	"CompeteAI/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJwtHandler(cmdable)
	v := ioc.InitMiddlewares(cmdable, handler)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService, cmdable)
	toolRegistry := ioc.InitFirecrawlTools()
	chatService := ioc.InitChatService(toolRegistry)
	chatHandler := web.NewChatHandler(chatService)
	mcpHandler := web.NewMCPHandler(toolRegistry)
	engine := ioc.InitWebServer(v, userHandler, chatHandler, mcpHandler)
	return engine
}
