name: "CompeteAI"
mode: "dev"
port: 8084
version: "v0.0.1"
start_time: "20260521"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  mode: "dev"
  time_format: "2006-01-02 15:04:05"
  
  # 文件输出配置
  filename: "compete_ai.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  file_output_enabled: true
  file_output_compress: true
  
  # 控制台输出配置
  console_output_enabled: true
  console_output_colorful: true
  console_output_time_format: "2006-01-02 15:04:05"

mysql:
  host: 0.0.0.0
  port: 3308
  user: "********"
  password: "********"
  dbname: "compete_ai"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: 0.0.0.0
  port: 26379
  password: ""
  db: 0
  pool_size: 100